= 5.7.2 Release Notes

== Feature Updates

* Significant performance improvements by tuning database queries and caching.
* You can now enable database query logging from within the logging settings area of the Dashboard. This can be useful for developers. There is a new "Database Query Log" report in the Dashboard > System > Optimization section of the dashboard.

== Behavioral Improvements

* UX Improvements
** Show areas and hot spots when in add block mode.
** Less adversarial errors on publishing pages that haven't chosen page locations or names.
** Show empty area display names in page always.
* We now detect InnoDB table support on installation.
* Added a search button to the marketplace themes and add-ons pages.
* Added stack name to the stack detail page (thanks akodde).
* Default administrative route actions are now protected by canAccess - not just the view and submit actions.
* Improved Image Block. Cleaned up edit mode, removed old unused options, made constrain image by width/height work again, and fixed the behavior where link type couldn't be switched more than once in an edit session until a page was reloaded.

== Bug Fixes

* Fixed inability to choose local file to upload into the file manager ( you had to drag and drop or us an alternate uploading method.)
* Marketplace: Fixed showing of theme sets on the add-ons page in the marketplace.
* Marketplace: Made filter by set actually work.
* Fixed inability to scroll panels in older browser versions.
* Fixed -1 memory limit failing installation (thanks EC-Chris)
* Maintenance mode now works again.
* Fixed bug where SMTP settings weren't being honored when sending email.
* Fixed bug where user selector couldn't be used in a block or accessed in a dialog window.
* Fixed "Undefined class constant" error when activate page templates from a theme where those templates didn't have a corresponding icon in the core.
* Fixed page attribute display block breaking when being used with a file/image attribute type.
* Fixing bug where group sets couldn't be used in advanced permissions.
* Fixed bug grid handle resizing when adding grid-based layouts to areas that don't have the container enabled.
* Fixed bug where you could insert a link or an image into the Redactor rich text editor instance in the Image Slider block.
* Fixed dashboard errors when asset cache was turned on and social links attribute was used. (thanks Mnkras).
* Fixed bug where old database updates would attempt to be re-run by the Migrations scripts.
* Fixed bug where "Force upgrade" didn't work (thanks mlabrum)
* Miscellaneous bug fixes to account profile private message system.
* Fixed bug where "Exclude from Page List" custom attribute wasn't actually excluding pages from page lists (thanks SaschaGalley)
* Fixed bug where automatic header/footer assets from menu items were being included on pages and tools scripts where they weren't being displayed.
* Fixed bugs in user attribute sort and attribute set sorting.
* Fixed Image/File attribute form not loading all needed assets when rendered on single_page
* Fixed bug where core properties couldn't be removed from customizable search dialogs due to a javascript error.
* Attribute categories and keys can now be correctly packaged again (thanks cpill0789!)
* Fixed bug where changing a page template on a page where the target page template defaults for that page type had different blocks than the source page template defaults could result in a SQL error.
* Fixed http://www.concrete5.org/developers/bugs/5-7-1/use-exception-declaration-missing-in-concreteblocksformcontrolle/
* Fixed form block error with built-in captcha where enabling captcha would cause a javascript error on submitting form on subsequent occasions, making updating the form impossible.
* Fixed JavaScript error when changing advanced permissions from the sitemap.
* Fixed JavaScript error that occurred when switching between Blocks, Clipboard and Stacks sub-panels in the Add panel, that made reloading a requirement.
* Fixed "Trying to add theme throws "Class \Concrete\Attribute\Rating\Service does not exist" error on case-sensitive systems when installing a theme.
* Fixed float bug on get more blocks in add block panel on certain browsers.

== Developer Updates

* File selector widget now passes a zero for a file ID when saved with no files. This improves the file selector widget's performance with blocks that don't have custom controllers to handle this. (thanks infostreams).
* Although it's not strict AXMLS, developers can now specify "time" columns in their db.xml files by using the "time" type.
* By defining a configuration value of concrete.updates.enable_auto_update_core in your concrete.php override directory, you can make automatic updates happen transparently in the background any time a new concrete core is detected (note: the core must replace the previous core.)
