= concrete5 5.7 Editor's Guide
:doctype: book
:source-highlighter: coderay
:toc: left
:toclevels: 2
:imagesdir: images/editors
ifeval::["{backend}" == "html5"]
:imagesdir: https://raw.githubusercontent.com/concrete5/concrete5-documentation/master/src/images/editors
endif::[]


Looking for the 5.6 and Earlier Editors Guide? http://www.concrete5.org/documentation/using-concrete5[Head Here].

Most of the work you'll need to do with concrete5 happens right on the pages you want to edit.
This "In-Context Editing" is very intuitive.
See a typo? Fix it right there.
Want to add a page? Just go where you want it to show up and click Add Page.
In-context editing makes content management a breeze.

For more administrative duties (like adding users, customizing themes, getting reporting data, etc) there is a more traditional Dashboard.
You can get to Dashboard pages from the Dashboard drop down in the main toolbar, or by typing part of the Dashboard page name you're looking for into the Intelligent Search field.
You know you're on a Dashboard page because there's a big photo in the background that changes every day.

You can learn more about the whole system below. We suggest starting with the In-Context side and then moving on to the Dashboard.

== <<in-page-editing>>[In-Context Editing]

* <<in-page-editing_sign-in>>[Sign In]
* <<in-page-editing_the-toolbar>>[The Toolbar]
** <<in-page-editing_the-toolbar_page-edit-drop-down>>[Settings]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_composer>>[Composer]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_design>>[Design]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_seo>>[SEO]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_location>>[Location]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_attributes>>[Attributes]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_speed-settings>>[Caching]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_permissions>>[Permissions]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_versions>>[Versions]
*** <<in-page-editing_the-toolbar_page-edit-drop-down_delete>>[Delete]

<<in-page-editing_adding-pages>>[Adding Pages]

<<in-page-editing_block-areas>>[Block Areas]

* <<in-page-editing_block-areas_add-block>>[Add Block]
** <<in-page-editing_block-areas_add-block_content>>[Content]
** <<in-page-editing_block-areas_add-block_html>>[HTML]
** <<in-page-editing_block-areas_add-block_auto-nav>>[Auto-Nav]
** <<in-page-editing_block-areas_add-block_external-form>>[External Form]
** <<in-page-editing_block-areas_add-block_form>>[Form]
** <<in-page-editing_block-areas_add-block_page-list>>[Page List]
** <<in-page-editing_block-areas_add-block_file>>[File]
** <<in-page-editing_block-areas_add-block_image>>[Image]
** <<in-page-editing_block-areas_add-block_image-slider>>[Image Slider]
** <<in-page-editing_block-areas_add-block_search>>[Search]
** <<in-page-editing_block-areas_add-block_google-maps>>[Google Map]
** <<in-page-editing_block-areas_add-block_rss-displayer>>[RSS Displayer]
** <<in-page-editing_block-areas_add-block_video-player>>[Video Player]
** <<in-page-editing_block-areas_add-block_youtube-video>>[YouTube Video]
** <<in-page-editing_block-areas_add-block_survey>>[Survey]
** <<in-page-editing_block-areas_add-block_date-navigation>>[Date Navigation]
** <<in-page-editing_block-areas_add-block_next-and-previous-nav>>[Next & Previous Nav]
** <<in-page-editing_block-areas_add-block_tags>>[Tags]
** <<in-page-editing_block-areas_add-block_conversation>>[Conversations]
** <<in-page-editing_block-areas_add-block_faq>>[FAQ]
** <<in-page-editing_block-areas_add-block_topic-list>>[Topic List]
** <<in-page-editing_block-areas_add-block_share-this-page>>[Share this Page]
** <<in-page-editing_block-areas_add-block_social-links>>[Social Links]
** <<in-page-editing_block-areas_add-block_testimonial>>[Testimonial]
** <<in-page-editing_block-areas_add-block_page-attribute-display>>[Page Attribute Display]
** <<in-page-editing_block-areas_add-block_feature>>[Feature]
** <<in-page-editing_block-areas_add-block_horizontal-rule>>[Horizontal Rule]
** <<in-page-editing_block-areas_add-block_page-title>>[Page Title]
* <<in-page-editing_block-areas_add-from-marketplace>>[Add from Marketplace]
* <<in-page-editing_block-areas_add-layout>>[Add Layout]
* <<in-page-editing_block-areas_design>>[Design]
* <<in-page-editing_block-areas_stacks>>[Stacks]
* <<in-page-editing_block-areas_clipboard>>[Clipboard]
* <<in-page-editing_block-areas_custom-templates>>[Custom Templates]

<<in-page-editing_dashboard>>[Dashboard]

<<in-page-editing_sign-out>>[Sign Out]



== <<dashboard>>[The Dashboard]

* <<dashboard_sitemap>>[Sitemap]
** <<dashboard_sitemap_full-sitemap>>[Full Sitemap]
** <<dashboard_sitemap_flat-view>>[Flat View]
** <<dashboard_sitemap_page-search>>[Page Search]
* <<dashboard_files>>[Files]
** <<dashboard_files_file-manager>>[File Manager]
** <<dashboard_files_search>>[Search]
** <<dashboard_files_attributes>>[Attributes]
** <<dashboard_files_sets>>[File Sets]
** <<dashboard_files_image-editor>>[Image Editor]
** <<dashboard_files_image-thumbnails>>[Image Thumbnails]
* <<dashboard_reports>>[Reports]
* <<dashboard_users-and-groups>>[Members]
** <<dashboard_users-and-groups_find-users>>[Search Users]
** <<dashboard_users-and-groups_groups>>[User Groups]
** <<dashboard_users-and-groups_user-attributes>>[Attributes]
** <<dashboard_users-and-groups_add-user>>[Add User]
** <<dashboard_users-and-groups_add-group>>[Add Group]
** <<dashboard_users-and-groups_community-points>>[Community Points]
* <<dashboard_pages-and-themes>>[Pages and Themes]
** <<dashboard_pages-and-themes_themes>>[Themes]
*** <<dashboard_pages-and-themes_themes_inspect>>[Inspect]
*** <<dashboard_pages-and-themes_themes_mobile-theme>>[Mobile Theme]
** <<dashboard_pages-and-themes_page-types>>[Page Types]
*** <<dashboard_pages-and-themes_page-types_settings>>[Settings]
*** <<dashboard_pages-and-themes_page-types_add-a-page-type>>[Add a Page Type]
** <<dashboard_pages-and-themes_attributes>>[Attributes]
*** <<dashboard_pages-and-themes_attributes_built-in-attributes>>[Built-In Page Attributes]
** <<dashboard_pages-and-themes_single-pages>>[Single Pages]
** <<dashboard_pages-and-themes_page-templates>>[Page Templates]
*** <<dashboard_pages-and-themes_page-templates_defaults>>[Defaults]
*** <<dashboard_pages-and-themes_page-templates_add-page-type>>[Add Page Template]

<<dashboard_workflow>>[Workflow]

* <<dashboard_workflow_workflow-list>>[Workflow List]
* <<dashboard_workflow_waiting-for-me>>[Waiting for Me]
* <<dashboard_workflow_basic-workflow-setup>>[Basic Workflow Setup]
** <<dashboard_workflow_basic-workflow-setup_create-a-workflow>>[Create a Workflow]
** <<dashboard_workflow_basic-workflow-setup_attach-workflow-to-page-permissions>>[Attach Workflow to Page Permissions]
** <<dashboard_workflow_basic-workflow-setup_managing-workflow-items>>[Managing Workflow Items]

<<dashboard_add-functionality>>[Add Functionality]

<<dashboard_system-and-maintenance>>[System & Settings]

* <<dashboard_system-and-maintenance_basics>>[Basics]
** <<dashboard_system-and-maintenance_basics_site-name>>[Site Name]
** <<dashboard_system-and-maintenance_basics_bookmark-icons>>[Bookmark Icons]
** <<dashboard_system-and-maintenance_basics_rich-text-editor>>[Rich Text Editor]
** <<dashboard_system-and-maintenance_basics_languages>>[Languages]
** <<dashboard_system-and-maintenance_basics_time-zone>>[Time Zone]
** <<dashboard_system-and-maintenance_basics_accessibility>>[Accessibility]
** <<dashboard_system-and-maintenance_basics_social-links>>[Social Links]
* <<dashboard_system-and-maintenance_seo-and-statistics>>[SEO and Statistics]
** <<dashboard_system-and-maintenance_seo-and-statistics_pretty-urls>>[Pretty URLs]
** <<dashboard_system-and-maintenance_seo-and-statistics_tracking-codes>>[Tracking Codes]
** <<dashboard_system-and-maintenance_seo-and-statistics_search-index>>[Search Index]
** <<dashboard_system-and-maintenance_seo-and-statistics_excluded-url-word-list>>[Excluded URL Word List]
** <<dashboard_system-and-maintenance_seo-and-statistics_bulk-seo-tool>>[Bulk SEO Tool]
* <<dashboard_system-and-maintenance_files>>[Files]
** <<dashboard_system-and-maintenance_files_file-manager-permissions>>[File Manager Permissions]
** <<dashboard_system-and-maintenance_files_allowed-file-types>>[Allowed File Types]
** <<dashboard_system-and-maintenance_files_thumbnails>>[Thumbnails]
** <<dashboard_system-and-maintenance_files_file-storage-locations>>[File Storage Locations]
* <<dashboard_system-and-maintenance_jobs>>[Optimization]
** <<dashboard_system-and-maintenance_jobs_cache-and-speed-settings>>[Cache & Speed Settings]
** <<dashboard_system-and-maintenance_jobs_clear-cache>>[Clear Cache]
** <<dashboard_system-and-maintenance_jobs_automated-jobs>>[Automated Jobs]
* <<dashboard_system-and-maintenance_permissions-and-access>>[Permissions & Access]
** <<dashboard_system-and-maintenance_permissions-and-access_site-access>>[Site Access]
** <<dashboard_system-and-maintenance_permissions-and-access_task-permissions>>[Task Permissions]
** <<dashboard_system-and-maintenance_permissions-and-access_user-permissions>>[User Permissions]
** <<dashboard_system-and-maintenance_permissions-and-access_ip-blacklist>>[IP Blacklist]
** <<dashboard_system-and-maintenance_permissions-and-access_captcha-setup>>[Captcha Setup]
** <<dashboard_system-and-maintenance_permissions-and-access_spam-control>>[Spam Control]
** <<dashboard_system-and-maintenance_permissions-and-access_maintenance-mode>>[Maintenance Mode]
** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2>>[Advanced Permissions 2]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_enabling-advanced-permissions>>[Enabling Advanced Permissions]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_assign-permissions>>[Assign Permissions]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_edit-permissions>>[Edit Permissions]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_timed-permissions>>[Timed Permissions]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_copying-permissions>>[Copying Permissions]
*** <<dashboard_system-and-maintenance_permissions-and-access_advanced-permissions-2_area-block-and-file-permissions>>[Area, Block and File Permissions]

<<dashboard_system-and-maintenance_login-and-registration>>[Login & Registration]

* <<dashboard_system-and-maintenance_login-and-registration_login-destination>>[Login Destination]
* <<dashboard_system-and-maintenance_login-and-registration_public-profiles>>[Public Profiles]
* <<dashboard_system-and-maintenance_login-and-registration_public-registration>>[Public Registration]
* <<dashboard_system-and-maintenance_login-and-registration_authentication-types>>[Authentication Types]

<<dashboard_system-and-maintenance_email>>[Email]

* <<dashboard_system-and-maintenance_email_smtp-method>>[SMTP Method]
* <<dashboard_system-and-maintenance_email_email-importers>>[Email Importers]

<<dashboard_system-and-maintenance_attributes>>[Attributes]

* <<dashboard_system-and-maintenance_attributes_sets>>[Sets]
* <<dashboard_system-and-maintenance_attributes_types>>[Types]
* <<dashboard_system-and-maintenance_attributes_topics>>[Topics]

<<dashboard_system-and-maintenance_environment>>[Environment]

* <<dashboard_system-and-maintenance_environment_environment-information>>[Environment Information]
* <<dashboard_system-and-maintenance_environment_debug-settings>>[Debug Settings]
* <<dashboard_system-and-maintenance_environment_logging-settings>>[Logging Settings]
* <<dashboard_system-and-maintenance_environment_proxy-server>>[Proxy Server]

<<dashboard_system-and-maintenance_backup-and-restore>>[Backup & Restore]

* <<dashboard_system-and-maintenance_backup-and-restore_backup-database>>[Backup Database]
* <<dashboard_system-and-maintenance_backup-and-restore_update-concrete5>>[Update concrete5]

<<dashboard_system-and-maintenance_conversations>>[Conversations]

* <<dashboard_system-and-maintenance_conversations_settings>>[Settings]
* <<dashboard_system-and-maintenance_conversations_banned-words>>[Banned Words]
* <<dashboard_system-and-maintenance_conversations_community-points>>[Community Points]
* <<dashboard_system-and-maintenance_conversations_conversation-permissions>>[Conversation Permissions]

<<dashboard_stacks-and-blocks>>[Stacks & Blocks]

* <<dashboard_stacks-and-blocks_stacks>>[Stacks]
* <<dashboard_stacks-and-blocks_block-and-stack-permissions>>[Block & Stack Permissions]
* <<dashboard_stacks-and-blocks_block-types>>[Block Types]
