[[appendix_form-widget]]
= Form Widget Reference

The following service objects offer an easy way to build HTML input elements and custom Concrete5 interfaces.
These can be useful in custom dashboard pages and block editing interfaces.

== Form Helper Services

Some HTML helper functions exist as a part of the Form service.

[source,php]
----
$html = Core::make('helper/form');
----

This will give you an instance of the `Concrete\Core\Form\Service\Form` object, which has helper methods for comment HTML form elements like input, checkbox, etc...

http://concrete5.org/api/class-Concrete.Core.Form.Service.Form.html[API Reference]

== Custom Color Form Widget

Create a custom widget that allows you to select a color.

[source,php]
----
$html = Core::make('helper/form/color');
----

Returns an instance of `Concrete\Core\Form\Service\Widget\Color`.

http://concrete5.org/api/class-Concrete.Core.Form.Service.Widget.Color.html[API Reference]

== Date/Time Calendar & Time Selector Widget

Create a custom widget that allows you to choose dates on a calendar, with an optional time..

[source,php]
----
$html = Core::make('helper/form/date_time');
----

Returns an instance of `Concrete\Core\Form\Service\Widget\DateTime`.

http://concrete5.org/api/class-Concrete.Core.Form.Service.Widget.DateTime.html[API Reference]

== Page Selector Widget

Create a custom widget that allows you to choose a page from Concrete5's sitemap or page search.

[source,php]
----
$html = Core::make('helper/form/page_selector');
----

Returns an instance of `Concrete\Core\Form\Service\Widget\PageSelector`.

http://concrete5.org/api/class-Concrete.Core.Form.Service.Widget.PageSelector.html[API Reference]

== Rating Widget

Create a custom widget 1-5 star rating widget.

[source,php]
----
$html = Core::make('helper/form/rating');
----

Returns an instance of `Concrete\Core\Form\Service\Widget\Rating`.

http://concrete5.org/api/class-Concrete.Core.Form.Service.Widget.Rating.html[API Reference]

== User Selector Widget

Create a custom widget that allows you to choose Concrete5 users from a search interface.

[source,php]
----
$html = Core::make('helper/form/user_selector');
----

Returns an instance of `Concrete\Core\Form\Service\Widget\UserSelector`.

http://concrete5.org/api/class-Concrete.Core.Form.Service.Widget.UserSelector.html[API Reference]

== File Manager Selector

Create a custom widget that allows you to choose files from the file manager.
Choose from all files or limit by type.

[source,php]
----
$html = Core::make('helper/concrete/file_manager');
----

Returns an instance of `Concrete\Core\Application\Service\FileManager`.

http://concrete5.org/api/class-Concrete.Core.Application.Service.FileManager.html[API Reference]
