= Grouping Files with File Sets

File Sets are a useful way to organize files in concrete5.
A single file can be in multiple File Sets.
The file manager interface provides ways to filter by file sets, and developers can work with them through code easily as well.
Adding a file to a file set programmatically is easy:

[source,php]
----
$file = \Concrete\Core\File\File::getByID(1);
$set = \Concrete\Core\File\Set\Set::getByName('My File Set');
$set->addFileToSet($file);
----

Removing a file from a set is similar simple:

[source,php]
----
$set->removeFileFromSet($file);
----

== Creating a File Set Programmatically

Sometimes you want to create a file set programmatically.
For example, you're creating a custom package and you want all files of a certain type added to a particular file set.
Creating a file set programmatically is easy:

[source,php]
----
$set = \Concrete\Core\File\Set\Set::createAndGetSet(
    'My File Set', 
    \Concrete\Core\File\Set\Set::TYPE_PUBLIC
);
----

The File Set object has a few more API methods that might be useful.

== API

These are just a few examples of what can be done with the concrete5 File API.
Get more from the Page API docs:

http://concrete5.org/api/class-Concrete.Core.File.Set.Set.html[File Set API Reference]
