= Searching and Sorting with the FileList Object

Concrete5 provides the http://concrete5.org/api/class-Concrete.Core.File.FileList.html[Concrete\Core\File\FileList] object to make it easy for developers to query concrete5 for a list of files based on different criteria.
Any time you want to sort, search or otherwise filter a list of files you should use this object, as it checks permissions and provides a nice API to what is a fairly complex table structure underneath.

[source,php]
----
$list = new \Concrete\Core\File\FileList();
----

By default, this list will include every file in your site, since it's not filtered in any way.
It will only include files that the current user can see, based on permissions.

[source,php]
----
$files = $list->getResults();
----

This is an array of all the files in the file manager, with no limit.
Each entry is just a `\Concrete\Core\File\File` object.

== Basic Filtering Examples

=== Filter by File Type

File Type is a class constant on the `\Concrete\Core\File\Type\Type` class.
Available constants include:

* `\Concrete\Core\File\Type\Type::T_IMAGE` (= 1)
* `\Concrete\Core\File\Type\Type::T_VIDEO` (= 2)
* `\Concrete\Core\File\Type\Type::T_TEXT` (= 3)
* `\Concrete\Core\File\Type\Type::T_AUDIO` (= 4)
* `\Concrete\Core\File\Type\Type::T_DOCUMENT` (= 5)
* `\Concrete\Core\File\Type\Type::T_APPLICATION` (= 6)
* `\Concrete\Core\File\Type\Type::T_UNKNOWN` ( = 9)


[source,php]
----
$list->filterByFileType(\Concrete\Core\File\Type\Type::T_IMAGE);
----

=== Filter by Extension

[source,php]
----
$list->filterByExtension('png');
----

=== Filter By Keywords

[source,php]
----
$list->filterByKeywords('foobar');
----

Filtering by keywords is a simple like search against the filename, description, title, tags, username of uploader, as well as the textual representation of any file attributes that have been marked as "included in search index."

=== Filter By File Set

[source,php]
----
$set = \Concrete\Core\File\Set\Set::getByName('My File Set');
$list->filterBySet($set);
----

To include files in no sets

[source,php]
----
$list->filterByNoSet();
----

=== Filter By a Particular File Size (in KB)

[source,php]
----
// Only includes files that are between 1MB and 2MB in Size
$list->filterBySize(1024, 2048);
----

== Filter by Attribute

Filtering by attribute is easy:

[source,php]
----
// Only include files where "width" is 200 or greater.
$list->filterByAttribute('width', 200, '>=');
----

== Sorting

Sort by filename is ascending alphabetical order.

[source,php]
----
$list->sortByFilenameAscending();
----

Sort by File Set Display Order.

NOTE: in order to use this method, you must include a single file set in your filter methods.

[source,php]
----
$list->sortByFileSetDisplayOrder();
----

== Permissions

By default, permissions will be checked for every file retrieved in the result set.
Ignoring permissions for the logged-in user is easy:

[source,php]
----
$list->ignorePermissions();
----

== Custom Queries

The FileList class has been completely rewritten in concrete5 version 7 as reliant on the http://doctrine-dbal.readthedocs.org/en/latest/reference/query-builder.html[Doctrine DBAL QueryBuilder].
You can grab the underlying QueryBuilder object in order to operate on it directly from any FileList object:

[source,php]
----
$query = $list->getQueryObject();
----

== Subclassing

It's easy to subclass the FileList object.
http://www.concrete5.org/documentation/developers/5.7/working-with-pages/searching-and-sorting-with-the-pagelist-object/[Check out the PageList documentation for subclassing information – the principles are the same]

== Pagination

Once you have filtered your FileList object, you can use getResults() to get the list of File objects.
Many times, however, you'll want to retrieve just few results at a time.
For this, you'll want to use the Pagination object.

[source,php]
----
$pagination = $list->getPagination();
----

=== With Permissions

If your File list is honoring permissions, the $pagination object will be an instance of the http://concrete5.org/api/class-Concrete.Core.Search.Pagination.PermissionablePagination.html[Concrete\Core\Search\Pagination\PermissionablePagination] object.
This means that the entire result set (up to 1000) will be loaded and then segmented, with the permissions checker run against it.

=== Without Permissions

If your FileList object is ignoring permissions, it simply returns a basic http://concrete5.org/api/class-Concrete.Core.Search.Pagination.Pagination.html[Concrete\Core\Search\Pagination\Pagination] object, which is simpler.

Once you have a Pagination object it's a simple matter to operate on it.
You can get the total number of results

[source,php]
----
echo $pagination->getTotalResults();
----

You can get the total number of pages:

[source,php]
----
echo $pagination->getTotalPages();
----

You can determine whether paging is necessary

[source,php]
----
$pagination->hasNexPage();
$pagination->hasPreviousPage();
----

And you can get the current page's results:

[source,php]
----
$pagination->setMaxPerPage(10)->setCurrentPage(2);
$results = $pagination->getCurrentPageResults();
----

=== Rendering Pagination

Common pagination output HTML is supported, including Bootstrap 2, Bootstrap 3, Basic Pagination, and Concrete5's default styling (which is heavily Bootstrap 3 inspired.)

[source,php]
----
echo $pagination->renderDefaultView(); // Outputs HTML for Bootstrap 3, useful in the Dashboard, etc…
----

You can also render any pagination view supported by Pagerfanta from your Pagination object.
https://github.com/whiteoctober/Pagerfanta[More information available here].

== API Reference

There are additional filtering options and relevant methods available in the FileList class.
These are detailed in the API documentation:

http://concrete5.org/api/class-Concrete.Core.File.FileList.html[FileList API Reference]

http://concrete5.org/api/class-Concrete.Core.Search.Pagination.html[Pagination API Reference]
