[[working-with-blocks]]
== Working with Blocks
:doctype: book
:source-highlighter: coderay

Blocks are the foundation behind everything that a Concrete5 website visitor sees that can also be edited through the CMS. There are over thirty block types installed with the default Concrete5 site, and they encompass functionality from in-page rich text, multimedia elements like video and image sliders, and even interactive elements like forms and surveys. Blocks can easily be placed and edited by site editors, and likewise can easily be extended and even built from scratch by a developer. Here's everything you need to know about working with Concrete5 blocks, whether you want to do something as simple as modify the HTML a block outputs or dive into something more advanced, like creating your own custom block type.

* <<working-with-blocks_directory-structure-and-concepts>>[Directory Structure & Concepts]
* <<working-with-blocks_working-with-existing-block-types_modifying-the-default-view-template-for-a-core-block-type>>[Working with Existing Block Types]
** <<working-with-blocks_working-with-existing-block-types_modifying-the-default-view-template-for-a-core-block-type>>[Modifying the Default View Template for a Core Block Type]
** <<working-with-blocks_working-with-existing-block-types_creating-additional-custom-view-templates>>[Creating Additional Custom View Templates]
*** <<working-with-blocks_working-with-existing-block-types_creating-additional-custom-view-templates_creating-a-template-file>>[Creating a Template File]
*** <<working-with-blocks_working-with-existing-block-types_creating-additional-custom-view-templates_automatically-including-css-and-javascript-in-custom-templates>>[Automatically including CSS and JavaScript in Custom Templates]
*** <<working-with-blocks_working-with-existing-block-types_creating-additional-custom-view-templates_including-custom-templates-in-packages>>[Including Custom Templates in Packages]
*** <<working-with-blocks_working-with-existing-block-types_creating-additional-custom-view-templates_default-a-block-to-a-custom-template-in-a-theme>>[Default a block to a custom template in a theme]
** <<working-with-blocks_working-with-existing-block-types_using-a-custom-controller-for-a-core-block-type>>[Using a Custom Controller for a Core Block Type]
** <<working-with-blocks_working-with-existing-block-types_embedding-blocks-in-a-page-template>>[Embedding Blocks in a Page Template]
* <<working-with-blocks_creating-a-new-block-type_getting-started>>[Creating a New Block Type]
** <<working-with-blocks_creating-a-new-block-type_getting-started>>[Getting Started]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_overview>>[Overview]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_anatomy-of-a-block>>[Anatomy of a Block]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_php-controller>>[PHP Controller]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_adding-saving-and-rendering>>[Adding, Saving & Rendering]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_installing-your-custom-block-type>>[Installing Your Custom Block Type]
*** <<working-with-blocks_creating-a-new-block-type_getting-started_sample-block-hello-world>>[Sample Block: Hello World]
** <<working-with-blocks_creating-a-new-block-type_design-guidelines>>[Design Guidelines]
** <<working-with-blocks_creating-a-new-block-type_implementing-ajax-and-server-side-requests-in-a-block-add-edit-t>>[Implementing AJAX & Server-Side Requests in a Block Add/Edit Template]
** <<working-with-blocks_creating-a-new-block-type_making-blocks-cacheable>>[Making Blocks Cacheable for Better Performance]
** <<working-with-blocks_creating-a-new-block-type_enabling-composer-editing-for-block-type>>[Enabling Composer Editing for a Block Type]
** <<working-with-blocks_creating-a-new-block-type_disabling-in-edit-mode-and-clipboard>>[Disabling in Edit Mode & Clipboard View]
** <<working-with-blocks_creating-a-new-block-type_enabling-search-indexability>>[Enabling Search Indexability]
** <<working-with-blocks_creating-a-new-block-type_adding-help-to-blocks>>[Adding Help to Blocks]
** <<working-with-blocks_creating-a-new-block-type_screencast-building-an-audio-player>>[Screencast: Building an Audio Player]
** <<working-with-blocks_creating-a-new-block-type_registering-css-and-javascript>>[Registering and Requiring CSS & JavaScript]
** <<working-with-blocks_creating-a-new-block-type_block-type-sets>>[Grouping Block Types into Sets]
** <<working-with-blocks_creating-a-new-block-type_enabling-inline-editing>>[Enabling Inline Editing]
** <<working-with-blocks_creating-a-new-block-type_disabling-grid-container>>[Disabling Grid Container]
** <<working-with-blocks_creating-a-new-block-type_multiple-database-tables>>[Working with Multiple Database Tables]
** <<working-with-blocks_creating-a-new-block-type_interactive-blocks_overview>>[Interactive Blocks]
*** <<working-with-blocks_creating-a-new-block-type_interactive-blocks_overview>>[Overview]
*** <<working-with-blocks_creating-a-new-block-type_interactive-blocks_form-submissions>>[Example: Handling a Form Submission from a Block's View Layer]
*** <<working-with-blocks_creating-a-new-block-type_interactive-blocks_passing-data>>[Example: Passing Data from a custom URL into a Block's View Layer]
** <<working-with-blocks_creating-a-new-block-type_including-complex-form-widgets>>[Including Complex Form Widgets]
** <<working-with-blocks_creating-a-new-block-type_including-a-block-in-a-package>>[Including a Block in a Package]
