[[background_versions_5-7-1]]
= 5.7.1 Release Notes

== Feature Updates

* concrete5 can now once again connect to the concrete5.org marketplace to download themes and add-ons.
  The experience takes place through the dashboard and is much smoother than before.
* Community authentication is available as an authentication type.
  Attach a community authentication token to your concrete5 site through concrete5.org, and you an login with your concrete5.org account to your concrete5 site.
* You can now set your site's time zone through the Timezone settings page.
  Developers can set it through a configuration value.
* Sitemap Flat View is now available in the Dashboard again.
* You can now search for a specific block type in the add block panel.
* You can now override block type caching settings on a block-specific basis, through the Advanced menu option in the block menu.
  This menu also houses the Block name field now.
* We now ship with Twitter authentication available in the core.

== Behavioral Improvements

* We now show the message and the stack trace when errors occur during installation.
* Better detection of broken packages, no more throwing of exception if controller files are missing.
  Better detection of pre-5.7 packages (along with more helpful error messaging in package listing dashboard page.)
* Workflow names can now contain multibyte characters (thanks hissy)
* Improved scrolling behavior when scrolling the add block panel next to a long page on the right with a touchpad.
* Search pages in dashboard and front-end of the site have an improved appearance and a universal search button for easier non-keyboard navigation.
* We now check to see that PHP's asp_tags directive is turned off on installation.
* Elemental theme now supports fallback fonts (thanks mkly)
* FAQ block has better option names, better default behaviors, cleaner icons.
* Sample content replacement via packages now works again.
  For an example of this, check out the Holiday Yogurt theme in the marketplace.
* The redactor inline editor is now transparent.
* Better dashboard performance on mobile devices (thanks hissy)
* Better handling of multiple fonts in style customizer (thanks mkly)
* Better localization of My Account page (thanks hissy)
* Upon activating or installing a theme, the user is taken to the page templates screen.
  When page templates are activated from within a theme, they will use a matching PNG from the page template images directory (if one exists).
* Checking for PHP doc comment preservation on install to fix issues with eAccelerator (thanks mkly!)
* Rating attribute is now powered by font awesome, more easily skinnable.
* File names and descriptions are escaped in search results.
* Inline editing of design now no longer grays out the contents of the block being edited (thanks mkly!)
* Added the option to the Redactor rich text editor to open lightbox links as AJAX requests rather than just assuming they were always images.
* Installing a theme with a grid framework, creating gridded layouts and then switching to a theme that doesn't support a grid no longer causes errors.
* Certain database columns that were text are now longtext (thanks infostreams.)
* Added character set to email content types (thanks ojalehto)
* Use better encryption when generating authentication strings, if available (thanks sarciszewski )
* You can now specify whether theme LESS files should be compressed when processed into CSS (useful for debugging) on the Cache settings page.
* Removed Rename Stack and Duplicate Stack on Global Areas (since this isn't supported and doesn't make sense) and renamed the Delete Stack menu item on this page to Clear Global Area.

== Bug Fixes

* Rating attribute works again.
* Fixed bug in theme packages where theme's couldn't be customized (thanks myconcretelab.)
* Fixed bug where saving custom design styles or resetting custom design styles on a block or area broke edit mode, requiring a page reload (thanks mkly)
* Tables in Redactor rich text editor now have a dotted border around cells and headers.
* Fixed bug where including meta title on a composer form with page name made it impossible to save the page name.
* Fixed inability to save a custom template on a block pasted from the clipboard.
* Fixed bug where page would display JSON output instead of content when dragging multiple images into a front-end file manager instance.
* Page Selector now works with PHP form array syntax (and will work in custom attributes.) (thanks infostreams)
* Got rid of "foreach" errors that killed sites when global areas were renamed in the Dashboard.
* Fixed bug where hard-coding a block in a page with a custom template wasn't working (thanks infostreams.)
* Fixed bug where saving the file storage location to the same location for a file would result in that file being removed.
* Fix "If Conversations Banned Words are enabled, all message posting fails."
* Fix "After upvoting / downvoting a message, can't upvote / downvote it or any others, seemingly ever again"
* Fixed bug where JSON would show when hitting enter on a file password form (although the password would save.)
* Fixed http://www.concrete5.org/developers/bugs/5-7-0-4/referenceerror-ccmalert-is-not-defined/
* We no longer display page templates on the design dialog for single pages in the sitemap.
* Layouts are no longer available to add in global areas.
  These will return at a later point.
* Fixed inability to save configuration values on systems with Zend OpCache enabled.
* Fixed bug when attempting to render a stack display block with a custom style (thanks infostreams)
* Fixed bug where full page caching could break the login page.
* Fixed bug where you couldn't edit anything without a reload subsequently after editing a layout once.
* Fixed bug when attempting to grid layout columns with content in them.
* "Guest" and "Registered Users" groups now appear in the page-level permissions dialog in simple permissions mode.
* Fixed errors setting the title of the site and title of the page, along with incorrect url encoding, in the share this page block (thanks ojalehto).
* Fixed errors when visiting IP blacklist dashboard page on case sensitive file systems (thanks cpill0789!)
* Fixed bug where a block couldn't have a custom class and custom design properties attached to it (thanks jordif)
* Fixed mis-positioned block type icons in the blocks panel on non-Bootstrap3 themes.
* Fixed bug where area permissions weren't properly trickling down into layout sub-areas.
* Fixed bug where block permissions in layout sub-areas weren't properly inheriting from the sub-area.
* Add-ons in multiple languages should honor the selected language again (thanks mlocati).
* Fixed some IPv6 calculations (thanks EC-Joe)
* Fixing bug with packaged 404 page theme template not displaying properly.
* Fixed bug with Google maps block not working when added to a page twice (thanks brucewyne)
* Moving a block now prompts you to check a page in rather than simple exiting edit mode (leaving a page potentially unapproved.) (thanks mkly)
* Fixed http://www.concrete5.org/developers/bugs/5-7-0-4/google-web-fonts-ssl-error/
* HTML Block can now be copied to the clipboard without errors (thanks mlocati)
* Fixed http://www.concrete5.org/developers/bugs/5-7-0-4/class-concretecorepagestackglobalarea-not-found/ (thanks mkly)
* Fixed foreach error message when attempting to delete versions in versionl panel with no versions selected.
  Made it button become disabled after deleting versions (thank mlocati).
* Fixed delete error when deleting an instance of the FAQ block.

== Developers

* Parameters can now be added to closure controller routes.
* Extending the advanced search interface for pages, themes and users is easier now (thanks ijessup)
* We can now import name and description from themes by defining getThemeName() and getThemeDescription() in the theme's PageTheme class (thanks mlocati.)
