[[background_versions_5-7-3-1]]
= 5.7.3.1 Release Notes

== Feature Updates

* You can now preview a mobile theme in advanced permissions mode, when previewing a theme as user (thanks hissy!)

== Improvements

* Nicer language and country selection experience in the Multilingual Setup (thanks mlocati)
* Now when you are editing an existing page in composer, the URL slug field is read only, unless you click the edit pencil next to the slug.
* Image block now only displays images in the file manager when launching the file manager (thanks goutnet!)
* You can now click the pixel values in the area and block custom design pallette (rather than being forced to only use the slider.) (thanks olsgreen!)
* Dialog windows are resizable again (thanks goutnet)
* FAQ block now contains an instance of Redactor rich text editor rather than plain text.
* We won't generate .mo files for empty languages for Multilingual websites (fixes a bug with Zend Translation that doesn't work well with these) (thanks ezannelli)
* Google Maps block now provides support for scroll wheels (thanks NKay and EC-Joe)
* Modal windows should behave better on small screens (thanks hissy)
* Location lists now includes Japanese states (thanks kanetei and Katz)
* Validation and HTML improvements to the Image Slider blocks (thanks micrdy)
* Add block panel can now be pinned and will remain open (by clicking on the add block panel and clicking again.) (thanks goutnet!)
* Better checking on installation for the mbstring library (which is required due to a bug in the Patchwork i18n library)
* Form block now scrolls to the proper position on page (thanks Mainio)
* File manager now lets you choose how many results you want per page (thanks goutnet)
* Miscellaneous improvements to edit page in composer.

== Bug Fixes

* Custom jobs can now be installed again in the application/jobs directory.
* Lots of bug fixes to multilingual site content and site translations (thanks mlocati!)
* Fixed some issues with sample content import from themes and page feed objects that weren't present.
* User registration attributes now save properly when users register.
* Pages no longer change positions in sitemap if they are published through composer.
* Fixed bug where pages set to have their sub-pages inherit from page type permissions weren't accurately doing so.
* Fixed bug where changing a page author from the sitemap would close the dialog window if the page author was changed twice without reloading the page.
* Fixed bug where package database files (db.xml) weren't refreshed fully when updating packages (thanks DanK)
* Fix Translate Interface / Reload Strings - Exception if folders missing
* Fixed some cosmetic issues with the Translate Site Interface page.
* Fixed bug where reordering composer form elements wasn't working.
* Fixed bug where page type was cleared when updating page templates from the design panel (thanks mesuva)
* Sitemap flat view works in Safari again.
* Fixed error with "show system pages" always displaying even if you uncheck the check box on certain PHP configurations (thanks Nielsb85)
* Fixing 404 on edit page type outputs if clicking on icon
* Fixed bug where deleting composer form elements wasn't working.
* Page list block preview area now works again (thanks hissy)
* Miscellaneous code comments and bug fixes (thanks Mnkras)
* When pretty URLs were enabled, "index.php" was preserved in the redirect URLs.
  This is no longer the case (thanks Mainio)
* Duplicated pages now show up properly in the Next/Previous block.
* Proper default value for the switch language block.

== Developer Updates

* "on_page_view" event now passes back an argument "contents" which can be retrieved from the event, and the rendering library acts on the retrieved event, meaning that the rendered HTML can be acted on by events and passed back to the core (thanks Mainio)
* Added "on_cache_flush" global event that occurs whenever the entire application's caches are flushed (thanks Goutnet)
* Changed "on_page_view" block event to "on_block_load" (thanks Mainio)
* API fixes and tweaks to Mail Helper
* Flexible JavaScript and PHP API to control default filtering on the file manager, pass constants between PHP and JavaScript (thanks goutnet!)
