= Working with Files Programmatically

== Overview

While the File Manager provides a nice, powerful interface for working with files graphically, there are times when developers will want to set attributes on files, update their names, modify where they are stored and more.
This can all be done easily through the concrete5 API.

== Setting Attributes on an Existing File

Let's say we've created a file attribute of the checkbox type with the "is_featured" handle.
Setting this on a particular File object is easy.

[source,php]
----
$file = \File::getByID(3);
$file->setAttribute('is_featured', true);
----

That's it! More complex attribute types may take more complex values in the second argument.
For example, if you have a select attribute with the handle "selected_color" for a particular file and you want to set it programmatically, the Select attribute type expects its value to be an array of values that match the available options stored in the particular attribute.
If we have a select attribute for colors that contains "Red," "Yellow," and "Green", selecting Red and Green for a particular file can be done like this:

[source,php]
----
$file = \File::getByID(3);
$values = array('Red', 'Green');
$page->setAttribute('selected_color', $values);
----

== Updating a File's Name or Description

The http://concrete5.org/api/source-class-Concrete.Core.File.Version.html[File Version] class contains a numbmer of helpful, easy-to-use API methods to modify that version's properties.
Whenever working with this class, make sure to start by calling getVersionToModify() on the relevant File object.
This will return a new Version of the File object (if necessary), so that you can rollback to a previous version if necessary.

[source,php]
----
$file = \File::getByID(3);
$version = $file->getVersionToModify();
$version->updateTitle('New Title');
$version->updateDescription('New Description');
----

== Setting a new Storage Location

Concrete5 version 7 introduces a new object for storage locations.
Storage locations can be defined in the Dashboard.
Most of the time a storage location will be a particular directory on your web server (in or out of the web root) – but additional storage locations like Amazon S3 or Dropbox are also possible.
Let's say we have a file in the default storage location, and we want to move it to Amazon S3.
Our Amazon S3 storage location has the ID of 2.

[source,php]
----
$amazon = \Concrete\Core\File\StorageLocation\StorageLocation::getByID(2); // This is the ID of Amazon S3
$file = \File::getByID(3);
$file->setFileStorageLocation($amazon);
----

== Setting a password on a File

[source,php]
----
$file = \File::getByID(3);
$file->setPassword('supers3cret');
----

== Retrieve File Sets a particular File is In

[source,php]
----
$file = \File::getByID(3);
$file->getFileSets();
----

This returns an array of http://concrete5.org/api/class-Concrete.Core.File.Set.Set.html[\Concrete\Core\File\Set\Set] objects.

== Deleting a File Version

[source,php]
----
$file = \File::getByID(3);
$version = $file->getVersion(1); // Gets the first version – make sure this isn't approved!
$version->delete();
----

== Deleting a File

[source,php]
----
$file = \File::getByID(3);
$file->delete();
----

== API

These are just a few examples of what can be done with the concrete5 File API.
Get more from the Page API docs:

http://concrete5.org/api/class-Concrete.Core.File.File.html[File API Reference] http://concrete5.org/api/class-Concrete.Core.File.Version.html[File Version API Reference]
