[[blocks_create_getting-started_save]]
= Adding, Saving & Rendering

== Adding a Block

When a Concrete5 administrator drags a block type from the Add Panel into their page and drops it in an area, the add template is loaded.
If there is no add template, we automatically skip to #3 below.
If this block is set to allow inline editing, the content of this template is injected directly into the page, otherwise a Concrete5 dialog is loaded, set to the dimensions specified in the block controller's $btInterfaceWidth and $btInterfaceHeight variables.

=== Load the Add Template

When the add template is loaded, the add() method from the Controller is run (if it exists), giving a developer the opportunity to inject data into the add template from the method.
Then, the add.php file is rendered.

=== Submit Data to Server

When the block is submitted, first the validate() method from the Controller is run.
If a Concrete\Core\Error\Error object with errors is returned, these are displayed and the process terminates.
Otherwise, the save() method is run.

== Editing a Block

When a Concrete5 administrator clicks a block in edit mode, and chooses "Edit" from the menu, the following takes place:

=== Load the Edit Template

When the edit template is loaded, the edit() method from the Controller is run (if it exists), giving a developer the opportunity to inject data into the edit template from the method.
Then, the edit.php file is rendered.
Additionally, *the value for any column on the $btTable database table is automatically injected into the edit.php local scope.* This means that if your $bTable has a column entitled "content" and the value of that content for that block is "This is my content" you can simply do this in view.php

[source,php]
----
<input type="text" name="content" value="<?php echo $content; ?>" />
----

and "This is my content." will print.

=== Submit Data to Server

Submitting the edit form to the server runs the same processes as when adding the block for the first time.

== Viewing Block

When a Concrete5 administrator clicks a block in edit mode, and chooses "Edit" from the menu, the following takes place:

=== Load the Edit Template

When the view template is loaded, the view() method from the Controller is run (if it exists), giving a developer the opportunity to inject data into the edit template from the method.
Then, the view.php file or selected custom template is rendered.
Additionally, *the value for any column on the $btTable database table is automatically injected into the view.php local scope.* This means that if your $bTable has a column entitled "content" and the value of that content for that block is "This is my content" you can simply do this in view.php and "This is my content." will print.
