[[pages_pagelist]]
= Searching and Sorting with the PageList object

Concrete5 provides the http://concrete5.org/api/class-Concrete.Core.Page.PageList.html[Concrete\Core\Page\PageList] object to make it easy for developers to query Concrete5 for a list of pages based on different criteria.
Any time you want to sort, search or otherwise filter a list of pages you should use this object, as it checks permissions, takes care of aliasing and provides a nice API to what is a fairly complex table structure underneath.

[source,php]
----
$list = new \Concrete\Core\Page\PageList();
----

By default, this list will include every page in your site, since it's not filtered in any way.
It will exclude aliases, inactive pages (e.g. pages in the trash can or the drafts folder) and it will only include pages that the current user can see, based on permissions.

[source,php]
----
$pages = $list->getResults();
----

This is an array of all the pages in the page list, with no limit.
Each entry is just a page object.

== Basic Filtering Examples

Filter by a page type:

[source,php]
----
$list->filterByPageTypeHandle('blog_entry');
----

Include pages of several types

[source,php]
----
$list->filterByPageTypeHandle(array('blog_entry', 'press_release'));
----

Filter By Keywords (Simple)

[source,php]
----
$list->filterByKeywords('foobar');
----

Filtering by keywords is a simple like search against the name, description or text content of a page, as well as the textual representation of any page attributes that have been marked as "included in search index."

Filter By Keywords (Full Text)

[source,php]
----
$list->filterByFulltextKeywords('foobar');
----

Filters the name, description and text content fields using MySQL's FULLTEXT search indexing.

== Filter by Attribute

The PageList object contains a magic method to filter by attribute.
Simply add a StudlyCapsed attribute handle after filterBy and pass the data into the attribute:

[source,php]
----
$list->filterByExcludeFromNav(true);
----

The attribute's type determines what kind of data it takes in its filter methods.
For example, if the attribute is a topic, it can take a topic tree node:

[source,php]
----
$node = \Concrete\Core\Tree\Node::getByID(10);
$list->filterByBlogEntryTopic($node);
----

== Sorting

Sort by Post Date

[source,php]
----
$list->sortByPublicDate();
----

or

[source,php]
----
$list->sortByPublicDateDescending();
----

Sort by Name:

[source,php]
----
$list->sortByName();
----

Sort by Sitemap Display Order

[source,php]
----
$list->sortByDisplayOrder();
----

== Permissions and Including Atypical Pages

Ignore Permissions

[source,php]
----
$list->ignorePermissions();
----

Include unusual pages:

[source,php]
----
$list->includeInactivePages();
$list->includeAliases();
$list->includeSystemPages();
----

== Advanced

=== Custom Queries

The PageList class has been completely rewritten in Concrete 5.7 as reliant on the http://doctrine-dbal.readthedocs.org/en/latest/reference/query-builder.html[Doctrine DBAL QueryBuilder].
You can grab the underlying QueryBuilder object in order to operate on it directly from any PageList object:

[source,php]
----
$query = $list->getQueryObject();
----

=== Subclassing

It's easy to subclass the PageList object.
Here, take a look at a custom class that only displays pages of a certain type, with a custom attribute for handling whether pages are included:

[source,php]
----
<?php

namespace PortlandLabs\ClassifiedList;

use Concrete\Core\Page\PageList;

class ClassifiedList extends PageList
{
    /** @var bool */
    protected $includeInactive = false;

    public function __construct()
    {
        parent::__construct();

        $this->ignorePermissions();
        $this->filterByPageTypeHandle('classified');
        $this->setItemsPerPage(10);
        $this->sortByPublicDateDescending();
    }

    public function deliverQueryObject()
    {
        if (!$this->includeInactive) {
            $this->filterByClassifiedIsDeactivated(false);
        }

        return parent::deliverQueryObject();
    }

    public function includeInactive()
    {
        $this->includeInactive = true;
    }

    public function filterByActive($start, $end = null)
    {
        if (!$end) {
            $end = $start;
        }
        $this->filterByPublicDate(date('Y-m-d H:i:s', $end), '<=');
        $this->filterByAttribute('special_offer_end_date', date('Y-m-d H:i:s', $start), '>=');
    }
}
----

== Pagination

Once you have filtered your PageList object, you can use getResults() to get the list of pages.
Many times, however, you'll want to retrieve just few results at a time.
For this, you'll want to use the Pagination object.

[source,php]
----
$pagination = $list->getPagination();
----

=== With Permissions

If your page list is honoring permissions, the $pagination object will be an instance of the http://concrete5.org/api/class-Concrete.Core.Search.Pagination.PermissionablePagination.html[Concrete\Core\Search\Pagination\PermissionablePagination] object.
This means that the entire result set (up to 1000) will be loaded and then segmented, with the permissions checker run against it.

=== Without Permissions

If your PageList object is ignoring permissions, it simply returns a basic http://concrete5.org/api/class-Concrete.Core.Search.Pagination.Pagination.html[Concrete\Core\Search\Pagination\Pagination] object, which is simpler.

Once you have a Pagination object it's a simple matter to operate on it.
You can get the total number of results

[source,php]
----
echo $pagination->getTotalResults();
----

You can get the total number of pages:

[source,php]
----
echo $pagination->getTotalPages();
----

You can determine whether paging is necessary

[source,php]
----
$pagination->hasNexPage();
$pagination->hasPreviousPage();
----

And you can get the current page's results:

[source,php]
----
$pagination->setMaxPerPage(10)->setCurrentPage(2);
$results = $pagination->getCurrentPageResults();
----

=== Rendering Pagination

Common pagination output HTML is supported, including Bootstrap 2, Bootstrap 3, Basic Pagination, and Concrete5's default styling (which is heavily Bootstrap 3 inspired.)

[source,php]
----
echo $pagination->renderDefaultView(); // Outputs HTML for Bootstrap 3, useful in the Dashboard, etc...
----

You can also render any pagination view supported by Pagerfanta from your Pagination object.
https://github.com/whiteoctober/Pagerfanta[More information available here].

== API Reference

http://concrete5.org/api/class-Concrete.Core.Page.PageList.html[PageList API Reference]

http://concrete5.org/api/class-Concrete.Core.Search.Pagination.html[Pagination API Reference]
